ARG  FEDORA_VERSION=latest
FROM fedora:${FEDORA_VERSION}
RUN  dnf -y update \
  && dnf -y install libgpiod-utils python3-pip \
  && dnf clean all \
  && rm -rf /var/cache/yum

RUN dnf -y install i2c-tools 

WORKDIR /opt/app-root/src

COPY requirements.txt requirements.txt

RUN pip3 install -r requirements.txt